# Generated by Django 4.1.2 on 2022-11-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useraccount_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
